

 
const SORTING_METHODS = {
    ALPHABETIC : "ALPHABETIC",
    PRICE_LOW_TO_HIGH_DE: "PRICE_LOW_TO_HIGH_DE",
    PRICE_HIGH_TO_LOW_DE : "PRICE_HIGH_TO_LOW_DE",

    PRICE_LOW_TO_HIGH_NL: "PRICE_LOW_TO_HIGH_NL",
    PRICE_HIGH_TO_LOW_NL : "PRICE_HIGH_TO_LOW_NL",

    PRICE_LOW_TO_HIGH_GB: "PRICE_LOW_TO_HIGH_GB",
    PRICE_HIGH_TO_LOW_GB : "PRICE_HIGH_TO_LOW_GB",
    RANGE : "RANGE",
    EFFICIENCY : "EFFICIENCY",
    FASTCHARGING : "FASTCHARGING",
    ACCELERATION : "ACCELERATION"
}
export default  SORTING_METHODS;



